### ISSUE TITLE
GeneralizedDiceLoss training much harder than DiceLoss.

### ISSUE THREAD

**Issue by percyfan** [wolny/pytorch-3dunet#13]
Hi, thanks for your codes!
I'm trying different losses on my custom dataset, which is highly unbalanced dataset with 3 classes.

When I tried DiceLoss, it reduced to about 0.08 with in 80 epochs, and the result is acceptable.

But then I used GeneralizedDiceLoss, with the same model and optimizer, the training becomes so slow that takes 50 epochs to decrease to 0.75.

Any ideas why this happens?

**Comment by wolny** [comment]
Hi @percyfan. This might be related to the the bug that's been found in GDL, see: https://github.com/wolny/pytorch-3dunet/issues/14. It has been fixed now. In general if the data is highly unbalanced GDL should produce much better results. Also bear in mind that the values of the standard DiceLoss and GDL are not directly comparable.

**Comment by percyfan** [comment]
@wolny Thank you, it works!

**Comment by wolny** [comment]
I'm glad to hear that. Happy NN training!
