### ISSUE TITLE
Is something wrong with DGLloss？

### ISSUE THREAD

**Issue by BigSheep0217** [wolny/pytorch-3dunet#14]
Hi @wolny , I found there might be a mistake in GDLloss, but I'm not sure. The numerator and denominator are described as `intersect = (input * target).sum(-1) * class_weights` and `denominator = (input + target).sum(-1) * class_weights`, so the class_weights would be useless?

**Comment by wolny** [comment]
Hi @BigSheep0217. Looks like you're right. Great spot, let me double-check the equation and fix it. Cheers!

**Comment by wolny** [comment]
Should be fixed now: https://github.com/wolny/pytorch-3dunet/commit/07300ecddf1de5dc43dd4ccf1541813c4d734dcf
