### ISSUE TITLE
how to generate random input file with larger resolution?

### ISSUE THREAD

**Issue by yaohuaxin** [wolny/pytorch-3dunet#15]
I noticed that the input size of file "resources/random_label3D.h5" are 128x128x128.
Can I generate a random input with large input, such as 512x512x512?

**Comment by wolny** [comment]
hey @yaohuaxin,
sure you can easily generate arbitrary random data in python, e.g.:
```
import numpy as np
import h5py

filename = '...'
shape = (512, 512, 512)
with h5py.File(filename, 'w') as f:
    # create a random 3D tensor with uniform distirbution (simulates input data)
    f.create_dataset('raw', data=np.random.rand(*shape))
    # create a random 3D binary tensor (simulates target data)
    f.create_dataset('label', data=np.random.randint(0, 2, shape))
```

**Comment by DecentMakeover** [comment]
@wolny  when you are creating labels why are you doing random.randint(0,2,shape)) i mean what is the purpose of the (0,2) is 2 the number of labels?
