### ISSUE TITLE
what is the From Of the Data?

### ISSUE THREAD

**Issue by BigSheep0217** [wolny/pytorch-3dunet#2]
Hello！I am a graduate student and trying to rebuild 3DUnet by pytorch，And Ican not find useful information about that. Your code are inspired to me! Now i am reading your code，and I am not understand about the input_channel. I mean if i have the CT 3D data like 256x256x128，the input_channel would be 128？Or it means the depth of the pictureS such as three of RGB pictures? Excuse me for my poor english. (⁄ ⁄•⁄ω⁄•⁄ ⁄)Looking forward to your reply~

**Comment by wolny** [comment]
Hi @BigSheep0217. I'm glad to hear that you've been inspired by my code, feel free to use it for your research.
Regarding your question about the: `input_channels` is the number of channels in the input image (in case of RGB it would be 3 as you said).
If your working with a 3D stack of CT scan of the size 256x256x128, then those are your spatial dimension (e.g. D, H, W) and if you want to use 3D UNet you **cannot** treat any of those axis as a channels axis, cause that would imply 2D convolutions, but 3D UNet uses 3D convolutions entirely.

**Comment by BigSheep0217** [comment]
Hi @wolny , May I ask another question? I want to use your code, and am trying to fix it to my experiment. Roughly, I understand how it works. But there are some problems and questions.
Firstly, when I run the code train.`py with the train.py –-in-channels 1 –out-channels 1`, it comes the wrong message “RuntimeError: running_mean should contain 1 elements not 32”Is there special number of channels I haven’t found?
    Secondly, I still confused and don’t know build my own dataset. So I checked Pytorch document and your code about generate 3DDataset. It seems that the data are random data. The “raw_dims = (N, in_channels) + size” expends the dimension to form a dataset contain several units. Am I right?
Based on my understanding, if I want to generate my dataset, I need to change the `class Random3DDataset(Dataset)`, maybe I can change the N and size to the folder path and read the series images and reshape them to NxDxHxW?(⁄ ⁄•⁄ω⁄•⁄ ⁄)

**Comment by BigSheep0217** [comment]
Hi, May I ask another question? I want to use your code, and am trying to fix it to my experiment. Roughly, I understand how it works. But there are some problems and questions.
Firstly, when I run the code train.py with the –-in-channels 1 –out-channels 1, it comes the wrong message “RuntimeError: running_mean should contain 1 elements not 32”. Is there special number of channels I haven’t found?
Secondly, I still confused and don’t know build my own dataset. So I checked Pytorch document and your code about generate 3DDataset. It seems that the data are random data. The “raw_dims = (N, in_channels) + size” expends the dimension to form a dataset contain several units. Am I right?
Based on my understanding, if I want to generate my dataset, I need to change the class Random3DDataset(Dataset), maybe I can change the N and size to the folder path and read the series images and reshape them to NxDxHxW?

**Comment by huawenqing** [comment]
> Hi @BigSheep0217. I'm glad to hear that you've been inspired by my code, feel free to use it for your research.
> Regarding your question about the: `input_channels` is the number of channels in the input image (in case of RGB it would be 3 as you said).
> If your working with a 3D stack of CT scan of the size 256x256x128, then those are your spatial dimension (e.g. D, H, W) and if you want to use 3D UNet you **cannot** treat any of those axis as a channels axis, cause that would imply 2D convolutions, but 3D UNet uses 3D convolutions entirely.

so what the _input_channels_ should be in a 3D stack of CT scan?

**Comment by wolny** [comment]
Hi @BigSheep0217 the code should run just fine with the options you've provided (`-in-channels=1 -out-channels=1`), so it's hard to say where the problem is. Could you send me the whole stack trace of the error, so that I could debug the issue you're facing? (`RuntimeError: running_mean should contain 1 elements not 32` doesn't say much about where the error occured).

Regarding your data preparation: you are correct I used the random data just to demonstrate the usage of the code (the network is trained to fit to the random 3D dataset I gave it). I didn't use the real data, cause the data I'm working with are not publicly available, though I'll make soon make a tutorial of how to use my code with some publicly available 3D semantic segmentation datasets (e.g. CREMI).
In order to work correctly your data should have the following format:
* raw data: DxHxWxC, where D - depth, H - height, W - width (spatial dims), C - in-channels (channel dim)
* labels: DxHxWxC, where D - depth, H - height, W - width (spatial dims, same as raw data), C - out-channels (channel dim).
Then in order to train the network you want to give the network patches of your raw and labeled data (this is the batch of data you give to the network and its dimensionality is NxDxHxWxC, where N - batch size).
In order to do so you need to provide your own [Dataset](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#Dataset) implementation which returns patches of your raw or labeled data (see `Random3DDataset` for an example of how to do it using random data) . Then you just replace `train_dataset` and `val_dataset` in `_get_loaders` function and you're good to go.

**Comment by wolny** [comment]
@huawenqing it depends on the the CT scans you're working with. E.g. if your CT scans are gray-scale slices, then `input_channels=1`.

**Comment by huawenqing** [comment]
> @huawenqing it depends on the the CT scans you're working with. E.g. if your CT scans are gray-scale slices, then `input_channels=1`.


Can a pixel or voxel have multiple channels, I am a bit confused.
I will be very grateful if you can reply.

**Comment by wolny** [comment]
@huawenqing yes, your input image can have multiple channels. As an example: in an RGB encoded photo which has 3 channels (red, green, blue). That's why the first convolutional layer in a CNN networks used for ImageNet classification has `in_channels=3`.

**Comment by BigSheep0217** [comment]
Hi @wolny , thank you for your replay so patient. I have solved the error (RuntimeError: running_mean should contain 1 elements not 32). I have some mistakes in net structure about the number of feature maps. Finally, I use my data, and it works! I think there are more details that I need to understand.  I am really thank you, wish you happy!

**Comment by BigSheep0217** [comment]
> > @huawenqing it depends on the the CT scans you're working with. E.g. if your CT scans are gray-scale slices, then `input_channels=1`.
> 
> Can a pixel or voxel have multiple channels, I am a bit confused.
> I will be very grateful if you can reply.

Hi @huawenqing ,  my data is gray-scale, so my in_channels=1. Because the input_data is (N,C,D,H,W), N is the number of the data, C is the channels, and DHW are depth, hight and wide. So, my one channel data will be loaded in (N, 0,D,H,W), note the element 0. and if I want to load another data as a other channel, it will be loaded in (N, 1,D,H,W), and so on.
Actually, I load in different channels by `self.raw[data_id][0] = a`,`self.raw[data_id][1] = b` and so on, in Class My_Dataset(Dataset):, manually.(a,b are 3-D matrix).
maybe, those can help u.

**Comment by wolny** [comment]
Hi @BigSheep0217. I'm glad that it worked out for you. Just to let you know I've added some proper `DataLoaders` that read the data directly from a given HDF5 file and can be used for training/validation and prediction phase. Please have a look at https://github.com/wolny/pytorch-3dunet/blob/master/train.py#L76 for training or https://github.com/wolny/pytorch-3dunet/blob/master/predict.py#L150 for prediction.
Basic data augmentation is also supported (see https://github.com/wolny/pytorch-3dunet/blob/master/datasets/hdf5.py for more info).

Now given that your HDF5 file have the right structure, you can just pass the path and train the model or use a trained model for prediction.

**Comment by wolny** [comment]
So currently the model expects the data to be provided via the HDF5 file with the following structure:
* training
```
/raw - dataset containing the raw 3D/4D stack. The axis order has to be DxHxW/CxDxHxW
/label - dataset containing the label 4D stack. The axis order has to be CxDxHxW
```
* prediction
```
/raw - dataset containing the raw 3D/4D stack. The axis order has to be DxHxW/CxDxHxW
```

**Comment by dmortem** [comment]
Hi, @wolny 
Thanks for your code! Currently I hope to train 3D UNet on my own dataset, my question is how to use HDF5 file to store multiple samples? For example, I have raw data and label of 5 people, and the size of these 5 data is (184, 512, 512), (150, 512, 512), (154, 512, 512), (147, 512, 512), (117, 512, 512). Then can I put them into one HDF5 file? Or do I need to create five HDF5 files?

**Comment by wolny** [comment]
Hi @dmortem,

I was convinced that I've responded to your comment already, but looks like the submission failed. Anyway, going back to your question: it would be best to create 5 separate HDF5 files and just list them in your config file (e.g.: https://github.com/wolny/pytorch-3dunet/blob/master/resources/train_config.yaml#L63). The DataLoader will just concatenate them (see: https://github.com/wolny/pytorch-3dunet/blob/master/datasets/hdf5.py#L269)

You'd probably want to use e.g. 3-4 for training and 1 for validation, so you might just do:
```
  train_path:
    - 'person1.h5'
    - 'person2.h5'
    - 'person3.h5'
    - 'person4.h5'
  val_path:
    - 'person5.h5' 
```

**Comment by dmortem** [comment]
Hi @wolny ,

Thanks a lot! Currently your code worked fine on my dataset, and I really learned a lot from your code!

**Comment by wolny** [comment]
Hey @dmortem,

I'm glad to hear that. Good luck with your experiments.
