### ISSUE TITLE
    logger.info(f'Seed the RNG for all devices with {manual_seed}')                                                                  ^

### ISSUE THREAD

**Issue by huiminlatte** [wolny/pytorch-3dunet#20]
When i run: "python train.py --config resources/train_config_ce.yaml # train with DiceLoss", I encountered the following output: 

  File "train.py", line 85
    logger.info(f'Seed the RNG for all devices with {manual_seed}')
                                                                 ^
SyntaxError: invalid syntax

Do you know what is missin?

**Comment by wolny** [comment]
Hi there,
as you can see there is nothing wrong with this syntax, except if you're using an old Python. Please make sure that the Python version in your conda environment is 3.6+
