### ISSUE TITLE
what is the significance of overlapping stride in  training

### ISSUE THREAD

**Issue by kdlsw** [wolny/pytorch-3dunet#21]
Hi
I'm just wondering, as mentioned in the train_config.yaml config file. 
`# train stride between patches (make sure that the training patches overlap)`
Is there a significance of this overlap config other than generating more training data? 
Thank you.

**Comment by wolny** [comment]
Hi @kdlsw,

you're totally right, overlapping the patches is not essential to train the model. I removed the comment from the config.

The overlapping patches are important for prediction though in order to get smoother probability maps without the block artifacts.

**Comment by kdlsw** [comment]
> Hi @kdlsw,
> 
> you're totally right, overlapping the patches is not essential to train the model. I removed the comment from the config.
> 
> The overlapping patches are important for prediction though in order to get smoother probability maps without the block artifacts.

I understand, thank you!

**Comment by wolny** [comment]
No worries
