### ISSUE TITLE
How to train 3dunet model without cropping patch?

### ISSUE THREAD

**Issue by Wenlong-Shi** [wolny/pytorch-3dunet#22]
If the size of data is small and it can be wholly fitted in a GPU, is there any way to train the model on the whole data with little change to the code?

**Comment by wolny** [comment]
Hi @Wenlong-Shi,

sure your data doesn't have to fit into the GPU memory for you to be able to train it. Just give the path to your H5 file in the config and the data loader will automatically split your stack into 3D chunks for training.

**Comment by mahaling** [comment]
Can you explain how to not use the slice_builder class. My data is just Dx64x64 and I don't want to create patches of it for training or testing

**Comment by wolny** [comment]
Hi @mahaling,

you could just specify the `train_patch: [D, 64, 64]` and `train_stride: [D, 64, 64]` in the config (see: https://github.com/wolny/pytorch-3dunet/blob/master/resources/train_config_ce.yaml#L61) and the whole image will be loaded in a single patch.
