### ISSUE TITLE
How to solve this problem about "can't open train.py"

### ISSUE THREAD

**Issue by yimingyimi** [wolny/pytorch-3dunet#23]
![@3N{DA HP7Q3~XQ{Y(2J2UM](https://user-images.githubusercontent.com/43194046/58141236-3f81cd80-7c75-11e9-8171-38c180ad7254.png)

**Comment by wolny** [comment]
Hi,

just `cd` into the directory where you checked out the `pytorch-3dunet` repository. Also maybe do some basics linux terminal tutorial first, cause this issue is not really relevant here.
