### ISSUE TITLE
Should I use pretrained model

### ISSUE THREAD

**Issue by jfzhuang** [wolny/pytorch-3dunet#24]
Hi, I found that the project didn't provide pretrained model files. Should I use pretrained model or just train the model from scratch?

**Comment by huazai-1994** [comment]
Hi,Thank you for work! but could you please provide the pretrained model files?

**Comment by wolny** [comment]
Hi @jfzhuang and @huazai-1994. This project is a general purpose 3D UNet implementation and does not contain any pre-trained models.
