### ISSUE TITLE
multi class labels

### ISSUE THREAD

**Issue by DecentMakeover** [wolny/pytorch-3dunet#26]
Hi 

Thanks for sharing your work, instead of binary labels, if i want to predict multiple labels, is that modification going to work in this network?
i have 25 segmentation categories.

Any help is appreciated.

Thanks in advance.

#EDIT 

I also wanted to know what should be the value of the raw_internal_path and label_internal_path, is it the path where the image and labels are stored, if yes my true images are in the nii.gz format, will that work?

**Comment by wolny** [comment]
Hi there,
> Thanks for sharing your work, instead of binary labels, if i want to predict multiple labels, is that modification going to work in this network?

yes, the implementation will work out of the box, just make sure to specify the right number of output channels in the config and you're good to go.

> I also wanted to know what should be the value of the raw_internal_path and label_internal_path, is it the path where the image and labels are stored

yes

> my true images are in the nii.gz format, will that work?
anything that can be read into a numpy array with `h5py` will work, so just give it a try (tbh I never tried nii.gz format)
