### ISSUE TITLE
Predict.py has too many values to unpack

### ISSUE THREAD

**Issue by StuckinPhD** [wolny/pytorch-3dunet#30]
I have a 3 channel input and a 1 channel output. If I run ``predict.py`` on a trained model and a sample I get the following error:

> ValueError: too many values to unpack (expected 4)

I noticed the problem was from here: https://github.com/wolny/pytorch-3dunet/blob/master/predict.py#L68, where index gets the input channel slice as well, which then when added with the ``output_channel`` https://github.com/wolny/pytorch-3dunet/blob/master/predict.py#L77 creates a 5 dimensional index.

This is the reason I was getting the error.

Well I managed to fix this by stripping the input channel index by adding: 

`index = index[1:]`

right after getting it from the ``data_loader``. This fixed it and managed to produce an output.

Don't know if this is the "proper" fix but wanted to report it here.

Thanks

**Comment by wolny** [comment]
Hi @StuckinPhD,

there was indeed an issue with the 4D raw data and the solution is pretty much as you've described, i.e. checking if the input is 4D and discarding the channel slice via `index[1:]`.

I've pushed the fix in the latest commit, together with config files for training and testing on sample 4D raw data if someone would like to try it out (see: https://github.com/wolny/pytorch-3dunet/blob/master/resources/train_config_4d_input.yaml and https://github.com/wolny/pytorch-3dunet/blob/master/resources/test_config_4d_input.yaml).

Thanks for reporting the issue.
