### ISSUE TITLE
how can i train with my own data with format nii.gz

### ISSUE THREAD

**Issue by zz10001** [wolny/pytorch-3dunet#33]
Hi，@wolny
It is a awesome work，but can you give me some advice to train my own dataset（nii or dcm)detail,thanks for your kind help!
Best,
dalian

**Comment by haoyangwu** [comment]
Hey,
You can use nibabel to get your data into numpy arrays, and them use h5py to store your data into h5.

**Comment by wolny** [comment]
Hey @zz10001,

since only the H5 format is supported in the implementation, I'd advise you to follow the suggestion from @haoyangwu.
