### ISSUE TITLE
Does not work with 4D data

### ISSUE THREAD

**Issue by antonioricciardi16** [wolny/pytorch-3dunet#35]
Despite the paper describing this algorithm being applied to 4D data (3-channel 3D input data), the code provided does not work on such data.

The random_label4D.h5 dummy dataset provided has 3 channels only in the output (label), but not in the input (raw). Using this dataset as train and validation set, and after setting in_channels = 1 and out_channels = 3 in the configuration file, an assertion error is encountered:

assert m.ndim == 3
AssertionError

This error was produced by the ElasticDeformation class. After disabling elastic deformation in the configuration file, this error appears:

ValueError: Expected target size (1, 32, 64, 64), got torch.Size([1, 3, 32, 64, 64])

To fully emulate the data used in the actual study, I created a 4D dummy dataset both in the input and output data:

import h5py
import numpy as np
f = h5py.File('random_label4D.h5', 'r')
g = h5py.File('random_4D.h5', 'w')
g.create_dataset('raw', data = np.stack((f['raw'], f['raw'], f['raw'])))
g.create_dataset('label', data = f['label'])
g.close()
f.close()

After setting in_channels = 3 and out_channels = 3, the same errors are obtained. Clearly this code does not reflect the one used in the paper.

**Comment by zzz123xyz** [comment]
Hi
I have the same error, I cannot use the dice loss in this code. Do you solve this problem at last? Thanks

**Comment by wuzihaoo** [comment]
> Hi
> I have the same error, I cannot use the dice loss in this code. Do you solve this problem at last? Thanks
I got the same problem. I noticed that you are using .nii file, me too. I just combine all my data to a big 3d file(e.g 2 files: DHW 32x256x256, 32x256x256, combine to a 64x256x256 file, so it's still 3d).
Do you solve this problem to run this code using 4d data? If so what's you .h5 data structure?
Thanks

**Comment by wuzihaoo** [comment]
The author has already answer this question I think
https://github.com/wolny/pytorch-3dunet/issues/16#issuecomment-484055086

**Comment by moizsajid** [comment]
I am also getting this same error with both ce and dice loss. Maybe @wolny can help us regarding this issue?

**Comment by wolny** [comment]
@antonioricciardi16, there was indeed a problem with `ElasticDeformation` transform not supporting the 4D tensors. I fixed the issue, see https://github.com/wolny/pytorch-3dunet/issues/36#issuecomment-547503204. 
Regarding the other issue you've mentioned:
> ValueError: Expected target size (1, 32, 64, 64), got torch.Size([1, 3, 32, 64, 64])

clearly you're using a target tensor of incorrect shape. If you're using the `CrossEntropyLoss` when training the model it won't work since the CE loss supports 4D tensors as targets, see PyTorch docs: https://pytorch.org/docs/stable/nn.html#crossentropyloss
