### ISSUE TITLE
variable for class weights different than what is called in losses.py

### ISSUE THREAD

**Issue by danarteaga** [wolny/pytorch-3dunet#37]
In the .yaml file, the variable that is declared is: loss_weight
However, in losses.py, the call to this variable is:
          >> weight = loss_config.get('weight', None)
It will thus always return None, as there is no 'weight' variable that is defined.

Instead, this should read:
          >> weight = loss_config.get('loss_weight', None)

**Comment by wolny** [comment]
Hi @danarteaga,

you're right that's an error. I've change the YAML config files to reflect that, i.e. changed `loss_weight` to `weight`. See: 1c167df6552a642d5cfc2142b5570d465c66acb0
