### ISSUE TITLE
Predictions in binary format?

### ISSUE THREAD

**Issue by mahaling** [wolny/pytorch-3dunet#40]
The code works great!. Thanks for that. 
The predict.py code produces a hdf5 file out of which I try to create a numpy ndarray which I want to write as a stacked tiff. But the problem is that the predictions are in float32 format (values between 0 and 1). 

Is there a way to get a binary mask as prediction or convert the float32 predictions to a binary stacked tiff file?.

Any help is appreciated. Thanks.

**Comment by mahaling** [comment]
can anyone help me with this please?.. Thanks

**Comment by vivian-wong** [comment]
Hi @mahaling , would you mind sharing how you figured it out? Somehow trained with binary labels, my predicted output is (2,D,W,H), not just (D,W,H), and I can't figure out what the 2 is.

**Comment by mahaling** [comment]
In predict.py there is a line (111) which says
prediction_map = prediction_map / normalization_mask

I added the following line of code after the above line of code

prediction_map_binary = np.array(np.where(prediction_map > threshold, 1, 0))

Where threshold is a value between 0 and 1 that you set that sets all values less than threshold to 0 and greater than threshold to 1, thus creating a binary map for me. 

The 2 in (2,D,W,H) is the number of prediction maps for each class that you have trained with. Index 0 pointing to class 0 (usually background) and index 1 pointing to class 1 (the object you want to segment).

**Comment by moizsajid** [comment]
@mahaling Do we have to threshold our predictions? Is there any way to avoid it? What would have happened if we had multiple classes?
