### ISSUE TITLE
Train on multiple GPUs

### ISSUE THREAD

**Issue by mahaling** [wolny/pytorch-3dunet#44]
I have a machine with multiple GPUs and I am trying to modify the code to make it train on multiple GPUs. Are there any pointers that someone can give if they have trained it successfully on multiple gpus. 

I changed the batch_size in the "get_train_loaders" function to match the number of GPUs. 
I added a line of code in main.py to set model = nn.DataParallel(model) for parallelization. 

While training from scratch the loaders are working fine, but I get the following error during evaluation I guess

Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 125, in main
    trainer.fit()
  File "pytorch-3dunet/unet3d/trainer.py", line 135, in fit
    should_terminate = self.train(self.loaders['train'])
  File "pytorch-3dunet/unet3d/trainer.py", line 195, in train
    eval_score = self.eval_criterion(output, target)
  File "pytorch-3dunet/unet3d/metrics.py", line 63, in __call__
    target = expand_as_one_hot(target, C=n_classes, ignore_index=self.ignore_index)
  File "pytorch-3dunet/unet3d/losses.py", line 321, in expand_as_one_hot
    return torch.zeros(shape).to(input.device).scatter_(1, src, 1)
RuntimeError: invalid argument 4: Index tensor must have same size as output tensor apart from the specified dimension at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/generic/THCTensorScatterGather.cu:324

If anyone had success training on multiple GPUs, please please reply. 

Thanks

**Comment by wolny** [comment]
Hi @mahaling,

yes, the `DataParallel` and changing the batch size is pretty much all you need to do to train on multiple GPUs. I wanted to make the list of GPU devices to be specified in the config and use `DataParallel` for multiple GPUs, but didn't find the time to do so, so far.
Your problem seems to be unrelated to multiple GPUs though... Could you check the shape of the input and target tensors you send to the validation metric function?

**Comment by wolny** [comment]
JTLYK: `DataParallel` and training on multiple GPUs is enabled by default in the current version: https://github.com/wolny/pytorch-3dunet/commit/c04c11366b7f0360dde9516014a5ab83795193a4
