### ISSUE TITLE
Ask Your random data

### ISSUE THREAD

**Issue by ZhangMingHui123** [wolny/pytorch-3dunet#47]
May i ask you that whether your random data each image has an mask or not?
I read the paper said that mask can be sparse labelled,which means some silces of the input images has the whole black mask?

**Comment by wolny** [comment]
Hi @ZhangMingHui123,

I don't use any masking in the example using randomly generated data. The implementation allows for that by specifying `ignore_index` in the config of the loss. See e.g. https://github.com/wolny/pytorch-3dunet/blob/master/unet3d/losses.py#L307
