### ISSUE TITLE
Has anyone tried to get this working on Windows?

### ISSUE THREAD

**Issue by victoryc** [wolny/pytorch-3dunet#52]
I understand that this code isn't supported on Windows. Has anyone tried to get this working on Windows? Does it require a lot of changes?
Thanks.

**Comment by danarteaga** [comment]
I have it running on Windows 10. The only important change that I remember making was to set the num_workers to 0 in the configuration file. Else, you will get a 'pickle local object' error - this took me almost a full week to figure out and almost destroyed my soul.
