### ISSUE TITLE
long dtype in test config file(s) does not work, should be int64

### ISSUE THREAD

**Issue by P1eter** [wolny/pytorch-3dunet#55]
To get the test (with config `resources/train_config_4D_input.yaml`) running, I needed to change the "long" dtype to "int64", otherwise I get a `RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target'` error in the loss function.

I only tested the mentioned file, but this might be relevant for more default configuration files.

I'm not sure why this is, but some very basic testing showed that in numpy `astype('long')` gives an array with dtype `np.int32`, which becomes a normal tensor when converting to pytorch with the `torch.from_numpy()` function, instead of a `torch.LongTensor`.

Tested with python 3.6.9

**Comment by victoryc** [comment]
Are you running on Windows  (which the author doesn't use)? See the closed thread https://github.com/wolny/pytorch-3dunet/issues/28 where I added a comment yesterday.

**Comment by P1eter** [comment]
Yes I'm pretty sure it was on Windows, but I can check that on Monday to be sure. The mentioned thread is indeed the same thing that I was experiencing. Maybe a comment about this in the code would be useful now that this is known (despite not officially supporting Windows), since using `int64` instead of `long` is an easy fix.

I will also close the issue, as Linux is listed as a prerequisite in the `README` and this happens only on Windows (judging by your listed thread). Thanks for your reply regardless.
