### ISSUE TITLE
Something wrong in the order of creating new env

### ISSUE THREAD

**Issue by SizheWei** [wolny/pytorch-3dunet#57]
In the readme.md, there is one line of code: 
`conda create -n 3dunet pytorch torchvision tensorboardx h5py scipy scikit-image scikit-learn pyyaml hdbscan pytest -c conda-forge -c pytorch
`
After creating the env, I typed 
`import torch` in python terminal, then I found that there is an error:
<img width="865" alt="Screenshot 2019-12-13 at 3 12 00 PM" src="https://user-images.githubusercontent.com/40791723/70777525-f9c85600-1dba-11ea-8f06-d2bb38f101c1.png">

Do you know how to fix it? Or are there any other methods to skip this problem?
Any help would be appreciated! Thanks!

**Comment by wolny** [comment]
You're invoking `ipython` which is not listed as a dependency for conda. Conda will install python 3.7+ and that is what you should be using. Just type `python` instead of `ipython` and you're good to go.
