### ISSUE TITLE
Error when logging model parameters and gradients

### ISSUE THREAD

**Issue by Hisham1990** [wolny/pytorch-3dunet#8]
Hello,
When I try your example training command:
`python train.py --checkpoint-dir ~/3dunet --in-channels 1 --out-channels 2 --layer-order crg --loss ce --validate-after-iters 100 --log-after-iters 50 --epoch 50 --learning-rate 0.0002 --interpolate --train-path resources/random_label3D.h5 --val-path resources/random_label3D.h5 --train-patch 32 64 64 --train-stride 8 16 16 --val-patch 64 128 128 --val-stride 64 128 128 `

I get the following error during logging:
`Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 211, in main
    trainer.fit()
  File "/home/hisham/Unet/pytorch-3dunet-master/unet3d/trainer.py", line 98, in fit
    should_terminate = self.train(self.loaders['train'])
  File "/home/hisham/Unet/pytorch-3dunet-master/unet3d/trainer.py", line 156, in train
    self._log_images(input, target, output)
  File "/home/hisham/Unet/pytorch-3dunet-master/unet3d/trainer.py", line 317, in _log_images
    self.writer.add_image(tag, image, self.num_iterations)
  File "/home/hisham/anaconda3/envs/3dunet/lib/python3.6/site-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/home/hisham/anaconda3/envs/3dunet/lib/python3.6/site-packages/tensorboardX/summary.py", line 211, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/home/hisham/anaconda3/envs/3dunet/lib/python3.6/site-packages/tensorboardX/utils.py", line 98, in convert_to_HWC
    assert(len(tensor.shape) == len(input_format)), "size of input tensor and input format are different"
AssertionError: size of input tensor and input format are different`

**Comment by Hisham1990** [comment]
I get ride of the error by passing the `dataformats` as follows
self.writer.add_image(tag, image, self.num_iterations, dataformats = 'HW')

**Comment by wolny** [comment]
Hi @Hisham1990. The script should work correctly given that you run in the conda environment defined in the README. Some people reported issues while logging images with `tensorboardX` before and usually the problem was an old version of `tensorboardX` in their conda env. I've tested it with `tensorboardX v1.4` and it works without errors. What version of `tensorboardX` are you using?

**Comment by farazkhan86** [comment]
Just to add to this, I also got the exact same error reported by @Hisham1990. I'm using ``TensorBoardX`` version ``1.6``.

The reason being that the image given to the writer is of the shape ``[H, W]`` whereas the default value of ``dataformat`` is ``CHW``:

`def add_image(self, tag, img_tensor, global_step=None, walltime=None, dataformats='CHW'):`

I too managed to get rid of this error by specifying the correct dataformat in ``trainer.py:319``

`self.writer.add_image(tag, image, self.num_iterations, dataformats='HW')`

**Comment by wolny** [comment]
Hi @farazkhan86. Thanks a lot for providing me with the version of the `tensorboarX` your using. Indeed after upgrading `tensorboardX` to `v1.6` in my conda environment I get the very same error. Looks like `tensorboarX` broke the backward compatibility between minor version changes (`1.4 -> 1.6`).
I've fixed the error according to your suggestions and updated the `README` saying that `tensorboardX v1.6` should be used from now on.
Thanks for reporting @Hisham1990.
